title: ulissesalmeida
email: anizark@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Posts about software development. It contains personal experiences,
  lessons learned and personal tastes. You may find helpful stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ulisses.dev"
twitter_username: ulissesalmeida
github_username:  ulissesalmeida
markdown: kramdown
timezone: America/Sao_Paulo
lang: en
